package com.demo.constants

object DBConst{

    const val collectionUsers = "users"
    const val collectionConversations = "conversations"
    const val collectionChats = "chats"
    const val collectionMessages = "messages"
    const val collectionRestrictedCountries = "restrictedCountries"
    const val collectionTokens = "tokens"
    const val collectionCallhistory = "callhistory"

    const val docParticipants = "participants"

    const val contact_info = "contact_info"
    const val first_name = "first_name"
    const val last_name = "last_name"
    const val username = "username"
    const val search_username = "search_username"
    const val isUserEmailVerified = "isUserEmailVerified"
    const val image = "image"
    const val video = "video"
    const val sticker = "sticker"
    const val conversation = "conversation"
    const val last_message = "last_message"
    const val last_timestamp = "last_timestamp"
    const val gender = "gender"
    const val display_name = "display_name"
    const val email = "email"
    const val date_of_birth = "date_of_birth"
    const val createdDate = "createdDate"
    const val text = "text"
    const val timestamp = "timestamp"
    const val to_id = "to_id"
    const val type = "message_type"
    const val isBlocked = "isBlocked"
    const val friendStatus = "friendStatus"
    const val addressLocation ="addressLocation"
    const val address ="address"
    const val latitude = "latitude"
    const val longitude = "longitude"
    const val message_status ="message_status"
    const val from_id = "from_id"
    const val video_thumbnail ="video_thumbnail"
    const val read = "read"
    const val chat_deleted_date = "chat_deleted_date"
    const val isChatDeleted = "isChatDeleted"
    const val isMediaUploadFailed = "isMediaUploadFailed"
    const val unreadCount = "unreadCount"
    const val fromName = "fromName"
    const val is_group = "is_group"
    const val readBy = "readBy"
    const val readAt = "readAt"
    const val islivesticker = "islivesticker"

    const val isGroup = "isGroup"
    const val GroupMembers = "GroupMembers"
    const val MemberStatus = "MemberStatus"
    const val isAdmin = "isAdmin"
    const val memberStatusInvite = "invite"
    const val memberStatusAdd = "add"
    const val memberStatusRemove = "remove"
    const val memberStatusLeft = "left"
    const val OtherInfo ="OtherInfo"
    const val CreatedType ="CreatedType"
    const val CreatorID ="CreatorID"
    const val CreatorName ="CreatorName"
    const val OtherUserID ="OtherUserID"
    const val OtherUserName ="OtherUserName"
    const val CreatedTypeCreate ="create"
    const val CreatedTypeChange ="change"
    const val groupName = "groupName"
    const val isInitialMember = "isInitialMember"
    const val forwarded = "forwarded"

    const val callType = "callType"
    const val callerID = "callerID"
    const val participate = "participate"
    const val roomDisplayImage = "roomDisplayImage"
    const val roomDisplayName = "roomDisplayName"
    const val roomName = "roomName"
    const val searchparticipate = "searchparticipate"
    const val callTypeVoice = "1"
    const val callTypeVideo = "2"
    const val historyID = "historyId"

    const val RING = "1"
    const val ACCEPT = "2"
    const val REJECT = "3"
    const val COMPLETE = "4"

    const val convId = "convId"
    const val id = "id"
    const val progress = "progress"
    const val imageBytes = "imageBytes"
    const val videoBytes = "videoBytes"
    const val videoThumbnailBytes = "videoThumbnailBytes"


    const val token = "token"
    const val createdAt = "createdAt"
    const val platform = "platform"

    const val statusAccept = "Accept"
    const val statusDecline = "Decline"
    const val statusBlock = "Block"
    const val statusPending = "Pending"
    const val statusCreated = "Created"

    const val isdisplayonline = "isdisplayonline"
    const val isonline = "isonline"
    const val currenttyping = "currenttyping"
    const val isdisplaytyping = "isdisplaytyping"
    const val isdisplayread = "isdisplayread"

}
